In [1]:
import tensorflow as tf
import numpy as np



In [3]:
n_inputs = 3
n_neurons = 5

X0 = tf.placeholder(tf.float32, [None, n_inputs])
X1 = tf.placeholder(tf.float32, [None, n_inputs])

Wx = tf.Variable(tf.random_normal(shape=[n_inputs, n_neurons],
                                 dtype=tf.float32))
Wy = tf.Variable(tf.random_normal(shape=[n_neurons, n_neurons],
                                 dtype=tf.float32))
b = tf.Variable(tf.zeros([1, n_neurons], dtype=tf.float32))

Y0 = tf.tanh(tf.matmul(X0, Wx) + b)
Y1 = tf.tanh(tf.matmul(Y0, Wy) + tf.matmul(X1, Wx) + b)

init = tf.global_variables_initializer()

In [5]:
import numpy as np

#Mini-batch
X0_batch = np.array([[0,1,2], [3,4,5],[6,7,8],[9,0,1]])#t = 0
X1_batch = np.array([[9,8,7], [0,0,0], [6,5,4], [3,2,1]])#t= 1

with tf.Session() as sess:
    init.run()
    Y0_val, Y1_val = sess.run([Y0, Y1], feed_dict = {X0: X0_batch, X1: X1_batch})
    

In [6]:
print(Y0_val)


[[ 0.9963177   0.2195449  -0.81610024  0.5215628  -0.889324  ]
 [ 1.         -0.07297775 -0.9998909   0.9267646  -0.6164906 ]
 [ 1.         -0.35346097 -0.99999994  0.9908528  -0.01996252]
 [ 1.         -0.99999994  0.9253871  -0.96804553  0.9999999 ]]


In [7]:
print(Y1_val)

[[ 1.          0.34728616 -1.          0.5687031   0.9999174 ]
 [-0.9998516   0.6981902  -0.74609625 -0.74460506  0.96454805]
 [ 1.         -0.4460138  -0.99999857  0.9096941   0.99990606]
 [ 1.         -0.382075   -0.9855604   0.9989305   0.76474285]]


In [8]:
#Exact same shut

X0 = tf.placeholder(tf.float32, [None, n_inputs])
X1 =  tf.placeholder(tf.float32, [None, n_inputs])


basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
output_seqs, states = tf.contrib.rnn.static_rnn(basic_cell, [X0, X1],
                                               dtype= tf.float32)
Y0, Y1 = output_seqs

W0828 17:28:48.580101 139688421295936 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

W0828 17:28:48.580887 139688421295936 deprecation.py:323] From <ipython-input-8-23c15b553be4>:7: BasicRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.SimpleRNNCell, and will be replaced by that in Tensorflow 2.0.
W0828 17:28:48.581668 139688421295936 deprecation.py:323] From <ipython-input-8-23c15b553be4>:9: static_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Plea

In [3]:
#Yet another but better
n_steps = 2
n_inputs = 3
n_neurons = 5

X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
X_seqs = tf.unstack(tf.transpose(X, perm=[1, 0 , 2]))
basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
output_seqs, states = tf.contrib.rnn.static_rnn(basic_cell, X_seqs,
                                               dtype=tf.float32)
outputs = tf.transpose(tf.stack(output_seqs), perm=[1, 0, 2])



W0828 17:46:13.524818 139643694634816 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

W0828 17:46:13.525806 139643694634816 deprecation.py:323] From <ipython-input-3-8cc978298229>:8: BasicRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.SimpleRNNCell, and will be replaced by that in Tensorflow 2.0.
W0828 17:46:13.526582 139643694634816 deprecation.py:323] From <ipython-input-3-8cc978298229>:10: static_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Ple

In [4]:

X_batch = np.array([
    [[0,1,2], [9,8,7]],
    [[0,3,8], [9,3,5]],
    
    [[6,2,2], [4,4,7]],
    [[3,4,7], [2,5,4]],
])
init = tf.global_variables_initializer()

In [5]:
with tf.Session() as sess:
    init.run()
    outputs_val = outputs.eval(feed_dict={X: X_batch})

In [7]:
print(outputs_val)

[[[-0.30619258  0.23034374 -0.28179723  0.6928438   0.61775434]
  [-0.9996485   0.9991265   0.9998968   0.99505794  0.80927765]]

 [[-0.9497578   0.2900066  -0.9385103   0.9923732   0.9947877 ]
  [-0.99999285  0.705539    0.9904258  -0.53584814  0.22631612]]

 [[-0.99816185  0.77920806  0.9933608  -0.25677195  0.24465328]
  [-0.9889694   0.9560949   0.93449426  0.9579106   0.99701387]]

 [[-0.99095035  0.8412203   0.5059318   0.9845843   0.97965634]
  [ 0.0099694   0.9934987   0.95735466  0.988956    0.85289   ]]]


In [2]:
#Training a RNN


n_steps = 28
n_inputs = 28
n_neurons = 150
n_outputs = 10

learning_rate = 0.001

X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
y = tf.placeholder(tf.int32, [None])

basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
outputs, states = tf.nn.dynamic_rnn(basic_cell, X, dtype=tf.float32)

logits = tf.layers.dense(states, n_outputs)
xentropy = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y,
                                                         logits=logits)
loss = tf.reduce_mean(xentropy)

optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate)
training_op = optimizer.minimize(loss)
correct = tf.nn.in_top_k(logits, y, 1)
accuracy = tf.reduce_mean(tf.cast(correct, tf.float32))

W0828 18:03:50.358140 140255179732800 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

W0828 18:03:50.359197 140255179732800 deprecation.py:323] From <ipython-input-2-1d251a3d933c>:14: BasicRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.SimpleRNNCell, and will be replaced by that in Tensorflow 2.0.
W0828 18:03:50.359916 140255179732800 deprecation.py:323] From <ipython-input-2-1d251a3d933c>:15: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
P

In [3]:
init = tf.global_variables_initializer()

In [4]:
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("/tmp/data/")
X_test = mnist.test.images.reshape((-1, n_steps , n_inputs))
y_test = mnist.test.labels

W0828 18:05:22.412092 140255179732800 deprecation.py:323] From <ipython-input-4-92a3bdd9779c>:3: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
W0828 18:05:22.412695 140255179732800 deprecation.py:323] From /root/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Please write your own downloading logic.
W0828 18:05:22.413472 140255179732800 deprecation.py:323] From /root/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:262: extract_images (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
I

Extracting /tmp/data/train-images-idx3-ubyte.gz
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Extracting /tmp/data/t10k-images-idx3-ubyte.gz


W0828 18:05:22.634971 140255179732800 deprecation.py:323] From /root/anaconda3/lib/python3.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:290: DataSet.__init__ (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


Extracting /tmp/data/t10k-labels-idx1-ubyte.gz


In [5]:
n_epochs = 100
batch_size = 150

with  tf.Session() as sess:
    init.run()
    for epoch in range(n_epochs):
        for iteration in range(mnist.train.num_examples // batch_size):
            X_batch, y_batch = mnist.train.next_batch(batch_size)
            X_batch = X_batch.reshape((-1, n_steps, n_inputs))
            sess.run(training_op, feed_dict= {X: X_batch, y: y_batch})
        acc_train = accuracy.eval(feed_dict= {X: X_batch, y: y_batch})
        acc_test = accuracy.eval(feed_dict={X: X_test, y:y_test})
        print (epoch, "Training accuracy:", acc_train, "Test accuracy: ", acc_test)

0 Training accuracy: 0.94 Test accuracy:  0.9084
1 Training accuracy: 0.9533333 Test accuracy:  0.9522
2 Training accuracy: 0.94666666 Test accuracy:  0.9607
3 Training accuracy: 0.98 Test accuracy:  0.9616
4 Training accuracy: 0.97333336 Test accuracy:  0.9657
5 Training accuracy: 0.98 Test accuracy:  0.9717
6 Training accuracy: 0.9866667 Test accuracy:  0.9704
7 Training accuracy: 0.97333336 Test accuracy:  0.9715
8 Training accuracy: 0.99333334 Test accuracy:  0.9749
9 Training accuracy: 0.97333336 Test accuracy:  0.9671
10 Training accuracy: 0.98 Test accuracy:  0.9703
11 Training accuracy: 0.99333334 Test accuracy:  0.976
12 Training accuracy: 0.96666664 Test accuracy:  0.971
13 Training accuracy: 0.97333336 Test accuracy:  0.9775
14 Training accuracy: 0.99333334 Test accuracy:  0.9731
15 Training accuracy: 0.98 Test accuracy:  0.9773
16 Training accuracy: 0.97333336 Test accuracy:  0.968
17 Training accuracy: 1.0 Test accuracy:  0.9763
18 Training accuracy: 1.0 Test accuracy:  0.

In [1]:
import tensorflow as  tf
import numpy as np


In [3]:
n_steps = 20 
n_inputs = 1
n_neurons = 100
n_outputs = 1

X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
y = tf.placeholder(tf.float32, [None, n_steps, n_outputs])

cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons, activation=tf.nn.relu)
outputs, state = tf.nn.dynamic_rnn(cell, X, dtype = tf.float32)

W0828 18:21:10.660581 139827971036992 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

W0828 18:21:10.661726 139827971036992 deprecation.py:323] From <ipython-input-3-3677a9768fc8>:9: BasicRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.SimpleRNNCell, and will be replaced by that in Tensorflow 2.0.
W0828 18:21:10.662415 139827971036992 deprecation.py:323] From <ipython-input-3-3677a9768fc8>:10: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Pl

In [4]:
cell = tf.contrib.rnn.OutputProjectionWrapper(
    tf.contrib.rnn.BasicRNNCell(num_units=n_neurons, activation=tf.nn.relu),
    output_size = n_outputs)

In [5]:
learning_rate = 0.001

loss = tf.reduce_mean(tf.square(outputs - y))
optimizer  =tf.train.AdamOptimizer(learning_rate=learning_rate)
training_op =optimizer.minimize(loss)

init = tf.global_variables_initializer()

In [ ]:
#now the execution

n_iterations = 1500
batch_size = 50

with tf.Session() as sess:
    init.run()
    for iteration in range(n_iterations):
        X_batch, y_batch = ###fuck it
        sess.run(training_op, feed_dict{X: X_batch, y:y_batch})
        if iteration% 100 == 0 :
            mse =loss.eval(feed_dict={X: X_batch,y: y_batch})
            print(iteration, "\tMSE:", mse)

In [ ]:
X_new = ##[...]
y_pred = sess.run(outputs, feed_dict={X: X_new})

In [7]:
#Deep RNN


n_neurons = 100 
n_layers = 3

layers = [tf.contrib.rnn.BasicRNNCell(num_units=n_neurons,
                                     activation=tf.nn.relu)
         for layer in range(n_layers)]



multi_layer_cell = tf.contrib.rnn.MultiRNNCell(layers)
outputs, states = tf.nn.dynamic_rnn(multi_layer_cell, X, dtype=tf.float32)

W0828 18:33:39.444575 139827971036992 deprecation.py:323] From <ipython-input-7-30994bfa2673>:13: MultiRNNCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.
